package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.47

import (
	"context"
	"errors"
	"log/slog"

	"github.com/PonomarevAlexxander/graphql-forum/internal/converter"
	"github.com/PonomarevAlexxander/graphql-forum/internal/errlib"
	"github.com/PonomarevAlexxander/graphql-forum/internal/gql/model"
)

// Update is the resolver for the update field.
func (r *commentMutationResolver) Update(ctx context.Context, obj *model.CommentMutation, input model.CommentUpdateInput) (model.CommentUpdateResult, error) {
	comment, err := r.s.Comment.Edit(ctx, *converter.GqlToDtoCommentUpdateInput(input))

	if err != nil {
		slog.Error(
			"Some error while trying to update Comment",
			"error", err.Error(),
		)

		if errors.Is(err, errlib.ErrNotFound) {
			return model.NotFoundError{Message: err.Error()}, nil
		}
		return model.InternalError{Message: err.Error()}, nil
	}

	return model.CommentUpdateOk{
		Comment: converter.DtoToGqlComment(comment),
	}, nil
}
